name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install system dependencies
      run: sudo apt-get install python3-distutils -y

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start MLflow server
      run: |
        nohup mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 127.0.0.1 --port 5000 &
      env:
        MLFLOW_TRACKING_URI: http://127.0.0.1:5000

    - name: Run MLflow Tracking
      run: |
        python train_model.py  # Ensure this script includes MLflow logging

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run tests with unittest
      run: |
        python -m unittest discover

    - name: Evaluate model
      run: |
        python evaluate_model.py

    - name: Build Docker image
      run: |
        docker build -t my_flask_app:latest .

    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 my_flask_app:latest
